const words = [
    { word: 'Azure ポリシー', mean: 'Azure リソースの管理とコンプライアンスを強化するためのツール', example: 'ポリシーを使用すると、リソースの作成や構成に関するルールを定義し、セキュリティやガバナンスの観点から適用できます。', answered: false },
    { word: 'リソースグループ', mean: 'Azureでリソースをまとめて管理するためのコンテナ', example: 'リソースグループにより、仮想マシンやストレージなどの関連リソースを一元管理できます。', answered: false },
    { word: '仮想マシン (VM)', mean: 'クラウド上で稼働するコンピュータ環境', example: 'AzureではWindowsやLinuxの仮想マシンを簡単に作成して運用できます。', answered: false },
    { word: 'Azure Storage', mean: 'クラウド上でスケーラブルなデータ保存が可能なサービス', example: 'BLOBやファイルストレージなど、様々なストレージ形式に対応しています。', answered: false },
    { word: '仮想ネットワーク (VNet)', mean: 'Azure内でのリソース同士の安全な通信を実現する仮想ネットワーク', example: 'VNetにより、クラウド内リソース間でプライベートに通信することができます。', answered: false },
    { word: '可用性ゾーン', mean: 'データセンター障害に備えた冗長性の高い構成', example: 'アプリを異なる可用性ゾーンにデプロイすることで、高可用性を実現します。', answered: false },
    { word: 'Azure AD (Entra ID)', mean: 'IDとアクセス管理を提供するサービス', example: 'Azure ADを使用して、ユーザー認証やSSO、多要素認証が実現できます。', answered: false },
    { word: 'スケーリング', mean: 'システムの処理能力を自動で拡大・縮小する仕組み', example: 'トラフィックの増加に応じて、リソースの自動スケーリングが行われます。', answered: false },
    { word: '料金計算ツール', mean: 'Azureサービス利用前にコストを試算できるWebツール', example: '事前にサービス構成を選んでコストを見積もることができます。', answered: false },
    { word: 'SLA (サービスレベルアグリーメント)', mean: 'Microsoftが提供するサービス稼働保証', example: 'SLAにより、稼働率の目標（例:99.9%）が提示され、信頼性を保証します。', answered: false },
    { word: 'Azure Portal', mean: 'Azureを操作するためのWebベースのGUIツール', example: 'Azure Portalからすべてのサービスを視覚的に操作できます。', answered: false },
    { word: 'CLI (コマンドラインインターフェース)', mean: 'コマンドラインベースでAzureを管理するツール', example: 'Azure CLIはスクリプトや自動化に適しており、DevOpsに活用できます。', answered: false },
    { word: 'ARM テンプレート', mean: 'Azureリソースのデプロイを自動化するJSON形式の構成ファイル', example: 'テンプレートを使うことで、インフラのコード化が可能になります。', answered: false },
    { word: 'Azure Functions', mean: 'サーバーレスで関数単位のコードを実行できるサービス', example: 'イベント駆動型アプリに適しており、インフラ管理が不要です。', answered: false },
    { word: 'Logic Apps', mean: 'ビジュアルにワークフローを構築する自動化サービス', example: 'メール通知やファイル転送などの業務プロセスを自動化できます。', answered: false },
    { word: 'App Service', mean: 'WebアプリをホスティングするPaaS型サービス', example: 'App Serviceを使うと、スケーラブルなWebアプリを迅速に構築可能です。', answered: false },
    { word: 'Azure Cosmos DB', mean: 'グローバル分散型のNoSQLデータベース', example: '高速でスケーラブルなアプリに最適なデータベースです。', answered: false },
    { word: 'Azure SQL Database', mean: 'マネージドなリレーショナルデータベースサービス', example: '自動バックアップやパッチ適用などを含むPaaS型のSQLサービスです。', answered: false },
    { word: 'パブリッククラウド', mean: '一般に提供されるクラウドコンピューティング環境', example: 'インターネット経由で誰でも利用可能なクラウドサービスです。', answered: false },
    { word: 'プライベートクラウド', mean: '企業内で利用される専用クラウド環境', example: 'セキュリティやコンプライアンスを重視する業種に適しています。', answered: false },
    { word: 'ハイブリッドクラウド', mean: 'オンプレミスとクラウドを組み合わせた環境', example: '一部のサービスをクラウド化しつつ、社内資産も活用できます。', answered: false },
    { word: 'Azure Monitor', mean: 'リソースの監視と可視化を行うサービス', example: 'メトリクスやログの収集・分析が可能で、障害予兆の検知にも使われます。', answered: false },
    { word: 'Azure Advisor', mean: 'ベストプラクティスに基づいた改善提案を提供', example: 'コスト削減やセキュリティ向上の推奨を自動で表示してくれます。', answered: false },
    { word: 'タグ', mean: 'リソースにメタ情報を付与する仕組み', example: '部署や用途などの情報をタグとして追加できます。', answered: false },
    { word: '課金レポート', mean: '利用料金やコスト分析のためのレポート', example: '日別やサービス別のコストを視覚的に確認できます。', answered: false },
    { word: 'Azure Marketplace', mean: 'サードパーティ製アプリやサービスの提供マーケット', example: 'Marketplaceを使えば、事前構成済みのソリューションを簡単に導入できます。', answered: false },
    { word: 'Azure DevOps', mean: '開発・運用プロセスを支援する統合サービス群', example: 'リポジトリ、CI/CD、テスト管理などが一体化されています。', answered: false },
    { word: 'リザーブドインスタンス', mean: '長期利用前提で割安に利用できる仮想マシン', example: '1年または3年契約でコストを大幅に削減できます。', answered: false },
    { word: 'Azure Blueprints', mean: 'ポリシーやARMテンプレートなどをまとめてデプロイできる枠組み', example: 'ガバナンスと一貫性を保ちながら環境構築が可能です。', answered: false },
    { word: 'Azure Bastion', mean: 'RDPやSSHをブラウザ経由で安全に提供するサービス', example: 'パブリックIPを使わずに仮想マシンへアクセスできます。', answered: false },
    { word: 'Network Security Group (NSG)', mean: '仮想ネットワーク内のトラフィックを制御するファイアウォール機能', example: 'NSGを使用して、特定のIPアドレスやポートからのアクセスのみを許可するルールを設定できます。', answered: false },
    { word: 'Azure Firewall', mean: 'VNetを保護するためのマネージドなクラウドベースのファイアウォールサービス', example: 'Azure Firewallは、悪意のあるトラフィックをブロックし、アプリケーションレベルの保護を提供します。', answered: false },
    { word: 'DDoS Protection', mean: '分散型サービス拒否(DDoS)攻撃からAzureリソースを保護するサービス', example: 'StandardレベルのDDoS Protectionを有効にすると、大規模な攻撃からもアプリケーションを保護できます。', answered: false },
    { word: 'VPN Gateway', mean: 'オンプレミス環境とAzureのVNetを安全に接続するためのゲートウェイ', example: 'VPN Gatewayを設置することで、インターネット経由で暗号化されたトンネルを構築し、社内ネットワークを拡張できます。', answered: false },
    { word: 'ExpressRoute', mean: 'Azureとオンプレミスを専用線で接続するサービス', example: 'ExpressRouteは、高い信頼性と帯域幅が求められるミッションクリティカルなシステム連携に利用されます。', answered: false },
    { word: 'Load Balancer', mean: '複数の仮想マシンにトラフィックを分散させるサービス', example: 'Webサーバーを複数台構成し、Load Balancerで負荷分散することで、可用性と応答性を向上させます。', answered: false },
    { word: 'Application Gateway', mean: 'Webアプリケーションのトラフィックを管理するロードバランサー', example: 'SSLオフロードやWeb Application Firewall(WAF)機能を提供し、セキュアなWebサイトを構築できます。', answered: false },
    { word: 'Content Delivery Network (CDN)', mean: '世界中のエッジサーバーにコンテンツをキャッシュし、高速に配信するサービス', example: 'CDNを利用して、画像や動画をユーザーの近くから配信することで、Webサイトの表示速度を改善します。', answered: false },
    { word: 'IaaS (Infrastructure as a Service)', mean: 'インフラ（サーバー、ストレージ、ネットワーク）を提供するクラウドサービスモデル', example: 'Azure Virtual MachinesはIaaSの一例で、ユーザーはOS以上のレイヤーを自由に管理できます。', answered: false },
    { word: 'PaaS (Platform as a Service)', mean: 'アプリケーション開発・実行環境を提供するクラウドサービスモデル', example: 'Azure App ServiceはPaaSであり、開発者はインフラを意識せずにコードのデプロイに集中できます。', answered: false },
    { word: 'SaaS (Software as a Service)', mean: 'ソフトウェアを提供するクラウドサービスモデル', example: 'Microsoft 365はSaaSの一例で、ユーザーはソフトウェアをインストールせずにブラウザ経由で利用できます。', answered: false },
    { word: 'CapEx (設備投資)', mean: '物理的なインフラを購入するための初期投資', example: 'オンプレミス環境では、サーバーやネットワーク機器の購入がCapExにあたります。', answered: false },
    { word: 'OpEx (運用コスト)', mean: 'サービスを利用するために継続的に発生する費用', example: 'クラウドサービスは利用量に応じた課金であり、OpExとして扱われるため、初期投資を抑えられます。', answered: false },
    { word: 'Azure Cost Management and Billing', mean: 'Azureの利用コストを監視、分析、最適化するためのツール群', example: 'このツールで予算を設定し、コストの異常をアラートで通知させることができます。', answered: false },
    { word: 'TCO計算ツール', mean: 'オンプレミス環境のコストとAzureへの移行コストを比較するツール', example: 'TCO計算ツールを使うことで、クラウド移行による総所有コストの削減効果を経営層に提示できます。', answered: false },
    { word: 'Azure サブスクリプション', mean: 'Azureサービスを利用するための課金単位および管理境界', example: '開発用と本番用でサブスクリプションを分けることで、請求と権限管理を明確に分離できます。', answered: false },
    { word: '管理グループ', mean: '複数のサブスクリプションをまとめて管理するための階層構造', example: '会社全体のポリシーを管理グループに適用することで、傘下の全サブスクリリプションにガバナンスを効かせられます。', answered: false },
    { word: 'ロールベースのアクセス制御 (RBAC)', mean: 'ユーザーの役割に応じてリソースへのアクセス権を付与する仕組み', example: '開発者には「共同作成者」ロールを、運用者には「閲覧者」ロールを割り当てて、最小権限の原則を徹底します。', answered: false },
    { word: 'Microsoft Defender for Cloud', mean: 'Azureリソースのセキュリティ体制を強化し、脅威から保護する統合サービス', example: 'Defender for Cloudは、セキュリティの推奨事項を提示し、脆弱性を可視化してくれます。', answered: false },
    { word: 'Azure Key Vault', mean: 'APIキー、パスワード、証明書などのシークレット情報を安全に管理するサービス', example: 'アプリケーションの接続文字列をKey Vaultに格納し、コードから直接参照することで安全性を高めます。', answered: false },
    { word: 'Azure Information Protection (AIP)', mean: 'ドキュメントやメールにラベルを付けて分類・保護するサービス', example: '「社外秘」ラベルが付いたファイルは、暗号化され、印刷やコピーが制限されます。', answered: false },
    { word: 'Microsoft Sentinel', mean: 'クラウドネイティブなSIEMおよびSOARソリューション', example: 'Microsoft Sentinelは、様々なログソースから脅威をインテリジェントに検出し、対応を自動化します。', answered: false },
    { word: 'Azure Service Health', mean: 'Azureサービスの問題、計画メンテナンス、正常性に関する情報を提供するサービス', example: 'Service Healthダッシュボードを確認することで、利用中のサービスに影響がある障害が発生しているか把握できます。', answered: false },
    { word: 'Azure Arc', mean: 'オンプレミスやマルチクラウド環境のリソースをAzureから一元管理するサービス', example: 'Azure Arcを使えば、オンプレミスのWindows ServerにもAzure Policyを適用できます。', answered: false },
    { word: 'Azure Migrate', mean: 'オンプレミスのサーバー、アプリ、データベースをAzureへ移行するためのツール群', example: 'Azure Migrateで既存環境を評価し、移行の計画を立て、実際に移行プロセスを実行します。', answered: false },
    { word: '可用性セット', mean: '同一データセンター内でVMを複数の物理ラックに分散させる機能', example: '可用性セットに2台のVMを配置することで、ハードウェア障害時にもサービスの継続性を確保します。', answered: false },
    { word: 'フォールトトレランス', mean: 'システムの一部に障害が発生しても、処理を継続できる能力', example: '複数のコンポーネントを冗長化することで、フォールトトレランスの高いシステムを設計します。', answered: false },
    { word: 'ディザスターリカバリー (DR)', mean: '大規模な災害時にシステムを復旧させるための計画やプロセス', example: 'DR計画では、別のリージョンにデータをバックアップし、有事の際にそちらでサービスを再開する手順を定めます。', answered: false },
    { word: 'Azure Site Recovery', mean: 'オンプレミスや別リージョンのVMをAzureにレプリケートし、DRを実現するサービス', example: 'Site Recoveryを設定しておけば、プライマリサイトが停止した際に、数分でAzure上のVMにフェールオーバーできます。', answered: false },
    { word: 'Azure Backup', mean: 'Azureやオンプレミスのデータを保護するためのバックアップサービス', example: 'Azure Backupを利用して、仮想マシンのデータを日次で自動的にバックアップし、長期保管します。', answered: false },
    { word: 'Cloud Shell', mean: 'ブラウザから直接利用できる、認証済みのコマンドライン環境', example: 'Azure Portal内からCloud Shellを起動し、すぐにAzure CLIやPowerShellコマンドを実行できます。', answered: false },
    { word: 'トラストセンター', mean: 'Microsoftのセキュリティ、プライバシー、コンプライアンスに関する情報を提供するWebサイト', example: 'トラストセンターで、Azureが各種の国際的な認証規格に準拠していることを確認できます。', answered: false },
    { word: 'コンプライアンス', mean: '法律、規則、業界標準などを遵守すること', example: '金融機関向けのシステムでは、FISCなどの厳しいコンプライアンス要件を満たす必要があります。', answered: false },
    { word: 'リージョン', mean: 'データセンターが配置されている特定の地理的な場所', example: '日本のユーザー向けサービスは、待機時間を短縮するために「東日本」または「西日本」リージョンにデプロイします。', answered: false },
    { word: '地理 (Geography)', mean: 'データ所在地、主権、コンプライアンス要件を保証する、1つ以上のリージョンを含む市場', example: '日本の「地理」は東日本と西日本リージョンで構成されており、データは国内に保持されます。', answered: false },
    { word: 'データ主権', mean: 'データが収集された国の法律や規制の対象となるという概念', example: 'ドイツの顧客データは、データ主権の要件により、ドイツ国内のデータセンターで管理する必要があります。', answered: false },
    { word: 'Azureサポートプラン', mean: '技術的な問題解決を支援するための、様々なレベルのサポート契約', example: '本番環境のシステムでは、迅速な対応が保証される「Standard」以上のサポートプランを契約することが推奨されます。', answered: false },
    { word: 'Azure Kubernetes Service (AKS)', mean: 'コンテナ化されたアプリケーションを管理するためのマネージドKubernetesサービス', example: 'AKSを利用することで、コンテナオーケストレーションの複雑な運用をAzureに任せることができます。', answered: false },
    { word: 'Azure Container Instances (ACI)', mean: '仮想マシンを管理せずに、単一のコンテナを迅速に実行できるサービス', example: '簡単なバッチ処理やタスクを実行するために、ACIでコンテナを数秒で起動します。', answered: false },
    { word: 'BLOBストレージ', mean: '画像、動画、ドキュメントなどの非構造化データを大量に格納するためのストレージ', example: 'Webサイトで利用するすべての静的ファイルをBLOBストレージにアップロードして配信します。', answered: false },
    { word: 'Azure Files', mean: 'クラウドベースのフルマネージドなファイル共有サービス (SMBプロトコル対応)', example: 'オンプレミスのファイルサーバーをAzure Filesに移行し、複数のVMから共有フォルダとしてマウントします。', answered: false },
    { word: 'Azure Virtual Desktop', mean: 'クラウド上でWindowsのデスクトップとアプリケーションを提供するサービス (DaaS)', example: 'リモートワーク環境を整備するために、Azure Virtual Desktopで社員にセキュアな仮想デスクトップ環境を提供します。', answered: false },
    { word: 'Azure Synapse Analytics', mean: 'データウェアハウスとビッグデータ分析を統合した分析サービス', example: 'Synapse Analyticsを使い、販売データとWebログを組み合わせて、包括的なビジネスインサイトを得ます。', answered: false },
    { word: 'Azure Machine Learning', mean: '機械学習モデルの構築、トレーニング、デプロイを支援する統合サービス', example: 'Azure Machine Learningの環境で、過去の販売データから将来の需要を予測するモデルを開発します。', answered: false },
    { word: 'Azure Cognitive Services', mean: '画像認識、音声認識、自然言語処理などのAI機能をAPIとして提供するサービス', example: 'Cognitive ServicesのVision APIを利用して、アップロードされた画像からテキストを抽出する機能を実装します。', answered: false },
    { word: 'Azure IoT Hub', mean: '多数のIoTデバイスとクラウド間で双方向の通信を安全に行うためのハブサービス', example: '工場のセンサーデータをIoT Hubに集約し、リアルタイムで機器の状態を監視します。', answered: false },
    { word: 'PowerShell', mean: 'タスクの自動化と構成管理のために設計されたコマンドラインシェルおよびスクリプト言語', example: 'PowerShellスクリプトを作成して、複数のリソースグループに同じ設定の仮想マシンを一度に作成します。', answered: false },
    { word: 'Azure Event Grid', mean: 'イベント駆動型アーキテクチャを容易に構築できる、フルマネージドなイベントルーティングサービス', example: 'BLOBストレージに新しいファイルが作成されたことをトリガーに、Event Grid経由でAzure Functionsを実行させます。', answered: false },
    { word: 'Azure Traffic Manager', mean: 'DNSベースのトラフィックロードバランサーで、グローバルにトラフィックを分散する', example: 'Traffic Managerを使い、ユーザーを最も近いリージョンのエンドポイントに誘導して、パフォーマンスを最適化します。', answered: false },
    { word: 'Azure DNS', mean: 'DNSドメインをホストし、名前解決を提供するためのサービス', example: '自社のドメイン「contoso.com」をAzure DNSで管理し、WebサイトのAレコードを登録します。', answered: false },
    { word: 'Azure Database for MySQL/PostgreSQL', mean: 'オープンソースのデータベースエンジンをベースにした、フルマネージドなリレーショナルデータベースサービス', example: '既存のLAMPスタックアプリケーションを、コードの変更を最小限に抑えてAzure Database for MySQLに移行します。', answered: false },
    { word: 'Azure Databricks', mean: 'Apache Sparkをベースにした、高速で共同作業が可能なビッグデータ分析プラットフォーム', example: 'データサイエンティストチームがAzure Databricksのノートブックを共有し、大規模なデータセットの分析を行います。', answered: false },
    { word: 'Azure App Configuration', mean: 'アプリケーションの構成設定を一元的に管理するサービス', example: '機能フラグや接続文字列をApp Configurationに保存し、アプリを再起動せずに設定を動的に変更します。', answered: false },
    { word: 'リージョンペア', mean: '同一地域内に存在する2つのリージョンの組み合わせで、災害復旧のために利用される', example: '東日本リージョンがプライマリの場合、西日本リージョンがリージョンペアとなり、障害発生時のフェールオーバー先として機能します。', answered: false },
    { word: '更新ドメイン (Update Domain)', mean: '計画メンテナンス時に同時に再起動されるVMのグループ', example: '可用性セット内のVMは複数の更新ドメインに分散され、メンテナンス中もサービス全体が停止しないようにします。', answered: false },
    { word: '障害ドメイン (Fault Domain)', mean: '共通の電源やネットワークスイッチを共有するハードウェアのグループ', example: '可用性セット内のVMは複数の障害ドメインに分散され、物理的なハードウェア障害の影響を最小限に抑えます。', answered: false },
    { word: 'Azure Government', mean: '米国政府機関とそのパートナー向けに設計された、特別なコンプライアンス要件を満たすAzure環境', example: '連邦政府のプロジェクトでは、セキュリティとコンプライアンスが強化されたAzure Governmentを利用する必要があります。', answered: false },
    { word: 'Microsoft Learn', mean: 'Microsoft製品に関する無料のオンライン学習プラットフォーム', example: 'AZ-900の試験対策として、Microsoft Learnの「Azureの基礎」ラーニングパスもあります。', answered: false },
    { word: 'リソースロック', mean: 'サブスクリプション、リソースグループ、リソースを誤った削除や変更から保護する機能', example: '本番環境の重要なデータベースには「削除不可」のロックを適用し、誤操作を防ぎます。', answered: false },
    { word: 'エラスティック (Elasticity)', mean: '需要の変動に応じて、コンピューティングリソースを迅速に増減させる能力', example: 'クラウドのエラスティックな性質により、オンラインセールのピーク時にサーバーを自動で増やし、終了後に減らすことができます。', answered: false },
    { word: 'アジリティ (Agility)', mean: '新しいITリソースを迅速にプロビジョニングし、市場の変化に素早く対応する能力', example: 'クラウドのアジリティを活用することで、新しいアプリケーションのアイデアを数週間ではなく数時間で試すことができます。', answered: false },
    { word: 'マルチテナント', mean: '単一のソフトウェアインスタンスやインフラを複数の顧客（テナント）で共有するアーキテクチャ', example: 'パブリッククラウドはマルチテナントモデルであり、リソースを共有することでコスト効率を高めています。', answered: false },
    { word: 'Azure Container Registry', mean: 'プライベートなDockerコンテナイメージを格納、管理、デプロイするためのサービス', example: '開発したコンテナイメージをAzure Container Registryにプッシュし、AKSから安全にプルして利用します。', answered: false },
    { word: '垂直スケーリング (スケールアップ)', mean: 'CPUやメモリなど、個々のリソースのサイズを大きくして性能を向上させること', example: 'データベースサーバーのパフォーマンスが不足したため、より高い性能を持つVMサイズにスケールアップしました。', answered: false },
    { word: '水平スケーリング (スケールアウト)', mean: 'リソースのインスタンス数を増やして性能を向上させること', example: 'Webサイトへのアクセスが増加したため、VMのインスタンス数を2台から4台にスケールアウトしました。', answered: false },
    { word: 'Azure Service Bus', mean: '信頼性の高いメッセージングを提供する、フルマネージドなエンタープライズ統合メッセージブローカー', example: '注文システムと在庫管理システムをService Busのキューを介して非同期に連携させ、システムの疎結合化を実現します。', answered: false },
    { word: 'サーバーレスコンピューティング', mean: '開発者がサーバーの管理を意識することなくコードを実行できるクラウドの実行モデル', example: 'Azure FunctionsやLogic Appsは、サーバーレスコンピューティングの代表的なサービスです。', answered: false },
    { word: '責任共有モデル', mean: 'クラウドプロバイダーと顧客の間で、セキュリティに関する責任範囲を明確にするモデル', example: 'IaaSではOSやアプリのセキュリティは顧客責任ですが、PaaSではプラットフォームまでがMicrosoftの責任範囲です。', answered: false },
    { word: 'Azure の基本 (Free) アカウント', mean: '特定のAzureサービスを一定期間または一定量まで無料で利用できるアカウント', example: 'Freeアカウントに登録して、実際に仮想マシンを作成し、Azure Portalの操作に慣れました。', answered: false },
    { word: '従量課金制 (Pay-As-You-Go)', mean: 'サービスを使用した分だけ料金を支払う課金モデル', example: '開発初期段階では、従量課金制でスモールスタートし、需要に応じてリソースを拡張できます。', answered: false },
    { word: 'Azure Hybrid Benefit', mean: 'ソフトウェアアシュアランス付きのWindows ServerやSQL ServerのライセンスをAzureで利用できる特典', example: 'Azure Hybrid Benefitを適用することで、Azure上の仮想マシンのコストを大幅に削減できます。', answered: false },
    { word: 'Azure スポット仮想マシン', mean: 'Azureの未使用のコンピューティング能力を大幅な割引価格で利用できるVM', example: '中断されても問題ないバッチ処理ジョブを、スポット仮想マシンで実行してコストを節約します。', answered: false },
    { word: 'Azure Dedicated Host', mean: '組織専用の物理サーバーを提供し、仮想マシンをホストするサービス', example: '厳しいコンプライアンス要件を満たすために、Dedicated Hostを使用して他のテナントから物理的に分離します。', answered: false },
    { word: '仮想マシン スケール セット (VMSS)', mean: '負荷に応じて自動的にスケーリングする、同一構成のVMのグループを作成・管理するサービス', example: 'VMSSを設定することで、トラフィックの急増時に自動でWebサーバーのインスタンスを増やせます。', answered: false },
    { word: 'マネージド ディスク', mean: 'Azureがストレージアカウントを自動で管理する、VM用のディスクストレージ', example: '現在では、可用性と管理の容易さから、VMにはマネージドディスクを使用するのが一般的です。', answered: false },
    { word: 'アンマネージド ディスク', mean: 'ユーザーが自身でストレージアカウントを管理する必要がある、旧来のVM用ディスク', example: '特別な理由がない限り、新規のデプロイメントでアンマネージドディスクを選択することはありません。', answered: false },
    { word: 'ストレージ アカウント', mean: 'Azure Storageのデータオブジェクト（BLOB, Files, Queues, Tables）を格納するためのコンテナ', example: 'アプリケーションのログを保存するために、新しいストレージアカウントを作成しました。', answered: false },
    { word: 'ストレージ層 (ホット、クール、アーカイブ)', mean: 'アクセス頻度とコストに応じて選択できるBLOBストレージのデータ層', example: '頻繁にアクセスするデータはホット層に、長期保存するバックアップはアーカイブ層に配置します。', answered: false },
    { word: 'geo冗長ストレージ (GRS)', mean: 'プライマリリージョンから数百マイル離れたセカンダリリージョンにデータを同期的にレプリケートする', example: '大規模災害に備えるため、GRSを選択してデータの地理的な冗長性を確保します。', answered: false },
    { word: 'ゾーン冗長ストレージ (ZRS)', mean: 'プライマリリージョン内の3つの可用性ゾーンにデータを同期的にレプリケートする', example: 'データセンターレベルの障害に耐える必要がある場合は、ZRSを選択します。', answered: false },
    { word: 'ローカル冗長ストレージ (LRS)', mean: 'プライマリリージョン内の単一のデータセンター内でデータを3回レプリケートする', example: 'コストを最も低く抑えたいが、データの耐久性も確保したい場合にLRSを選択します。', answered: false },
    { word: 'Azure Data Box', mean: '大量のデータをAzureに迅速かつ安価に転送するための物理的なアプライアンス', example: '数テラバイトのオンプレミスデータをネットワーク経由で転送する代わりに、Data Boxを注文して送付しました。', answered: false },
    { word: 'Azure Import/Export', mean: '顧客が提供した物理ディスクを使用して、Azureデータセンターとの間で大量のデータを転送するサービス', example: 'Import/Exportサービスを利用して、自社のハードディスクをAzureに送り、BLOBストレージにデータをインポートします。', answered: false },
    { word: 'Azure Table Storage', mean: '構造化されたNoSQLデータを格納するためのサービスで、スキーマレスな設計が特徴', example: '大量のユーザープロファイルデータを、スキーマを柔軟に変更できるTable Storageに格納します。', answered: false },
    { word: 'Azure Queue Storage', mean: '非同期処理を行うコンポーネント間で、大量のメッセージを格納・通信するためのサービス', example: '画像アップロード処理をQueue Storageにキューイングし、バックエンドのワーカーロールが非同期で処理します。', answered: false },
    { word: 'サブネット', mean: '仮想ネットワーク(VNet)をより小さなセグメントに分割したもの', example: 'Webサーバー層とデータベース層でサブネットを分け、NSGで間の通信を制御します。', answered: false },
    { word: 'VNet ピアリング', mean: '2つの仮想ネットワークを接続し、1つのネットワークとして通信できるようにする機能', example: 'グローバルVNetピアリングを使用して、異なるリージョンにあるVNet間をプライベートに接続します。', answered: false },
    { word: 'ルート テーブル', mean: 'Azureが仮想ネットワーク内のトラフィックをどこにルーティングするかを定義するルールセット', example: 'カスタムルートテーブルを作成し、特定のサブネットからのトラフィックを仮想アプライアンスに強制的に経由させます。', answered: false },
    { word: 'ネットワーク インターフェイス (NIC)', mean: 'Azure仮想マシンが仮想ネットワーク(VNet)と通信できるようにするコンポーネント', example: '1台のVMに複数のNICをアタッチして、異なるサブネットに接続することができます。', answered: false },
    { word: 'パブリック IP アドレス', mean: 'インターネットからAzureリソースに接続するために使用されるIPアドレス', example: 'WebサーバーにパブリックIPアドレスを割り当てて、外部からアクセスできるようにします。', answered: false },
    { word: 'プライベート IP アドレス', mean: '仮想ネットワーク内のリソース間で通信するために使用されるIPアドレス', example: 'VMはデフォルトでプライベートIPアドレスを持ち、同一VNet内の他のVMと通信します。', answered: false },
    { word: 'Azure Private Link', mean: '仮想ネットワークからAzure PaaSサービスや自社サービスへプライベートに接続する機能', example: 'Private Linkを使用して、パブリックインターネットを経由せずにVMからAzure SQL Databaseに安全に接続します。', answered: false },
    { word: 'Azure DNS Private Zones', mean: '仮想ネットワーク内でカスタムドメイン名を解決するためのDNSサービス', example: 'プライベートDNSゾーンを設定し、「db.internal」のような名前でプライベートIPアドレスを持つDBサーバーにアクセスします。', answered: false },
    { word: 'Web Application Firewall (WAF)', mean: '一般的なWebの脆弱性や悪用からWebアプリケーションを一元的に保護する機能', example: 'Application GatewayでWAFを有効にし、SQLインジェクションやクロスサイトスクリプティング攻撃を防ぎます。', answered: false },
    { word: 'Just-In-Time (JIT) VM アクセス', mean: '必要な時にのみ、指定された時間だけVMの管理ポート（RDP/SSH）を開く機能', example: 'JITアクセスを構成することで、管理ポートを常に開けておくことによるセキュリティリスクを低減します。', answered: false },
    { word: 'Azure AD Connect', mean: 'オンプレミスのActive DirectoryとAzure ADを同期させるためのツール', example: 'Azure AD Connectを導入し、オンプレミスのユーザーIDとパスワードでMicrosoft 365にサインインできるようにします。', answered: false },
    { word: '多要素認証 (MFA)', mean: 'パスワードに加えて、電話、SMS、認証アプリなど複数の要素で本人確認を行うセキュリティ強化策', example: 'すべてのグローバル管理者にMFAを必須に設定し、アカウントの乗っ取りを防ぎます。', answered: false },
    { word: '条件付きアクセス', mean: '「誰が」「どこから」「どのデバイスで」といった条件に基づいてリソースへのアクセスを制御するポリシー', example: '条件付きアクセスポリシーで、会社の管理外デバイスからの社内システムへのアクセスをブロックします。', answered: false },
    { word: 'Azure AD Identity Protection', mean: 'IDベースのリスク（漏洩した資格情報など）を自動的に検出・修復する機能', example: 'Identity Protectionが異常なサインインを検出した場合、ユーザーにMFAを要求したり、パスワードリセットを強制したりします。', answered: false },
    { word: 'Azure AD Privileged Identity Management (PIM)', mean: 'Azure ADやAzureリソースへの特権アクセスを管理、制御、監視するサービス', example: 'PIMを使用して、管理者ロールを永続的ではなく、必要な時に申請・承認を経てアクティブ化するようにします。', answered: false },
    { word: 'シングル サインオン (SSO)', mean: '一度の認証で、複数の連携するアプリケーションやサービスにアクセスできる仕組み', example: 'Azure ADをIDプロバイダーとして設定し、SaaSアプリケーションへのSSOを実現します。', answered: false },
    { word: 'B2B (Business-to-Business) コラボレーション', mean: '外部のパートナー企業のユーザーをゲストとして招待し、自社のリソースへのアクセスを許可する機能', example: 'Azure AD B2Bを使用して、共同プロジェクトのドキュメントを外部のコンサルタントと安全に共有します。', answered: false },
    { word: 'B2C (Business-to-Consumer)', mean: '顧客向けのWebサイトやモバイルアプリで、ID管理（サインアップ、サインインなど）を提供するサービス', example: 'Azure AD B2Cを導入し、エンドユーザーがSNSアカウントで自社サービスにログインできるようにします。', answered: false },
    { word: 'Azure AD Domain Services', mean: 'ドメインコントローラーをデプロイせずに、Azureでマネージドなドメインサービス（LDAP, Kerberosなど）を提供する', example: 'AzureにデプロイしたVMを、Azure AD DSが提供するマネージドドメインに参加させます。', answered: false },
    { word: 'サービス プリンシパル', mean: 'アプリケーションやサービスがAzureリソースにアクセスする際に使用されるID', example: 'CI/CDパイプラインがAzureにリソースをデプロイするために、サービスプリンシパルを作成し、適切なRBACロールを割り当てます。', answered: false },
    { word: 'マネージド ID', mean: 'Azureリソースに自動的に管理されるIDを付与し、Azure AD認証をサポートするサービスへの接続を容易にする機能', example: 'VMにマネージドIDを有効にし、コードに資格情報を含めることなくKey Vaultにアクセスします。', answered: false },
    { word: 'ログ分析ワークスペース (Log Analytics Workspace)', mean: 'Azure Monitorのログデータを集約、分析、可視化するための一元的なリポジトリ', example: '複数のVMからのログを単一のLog Analyticsワークスペースに収集し、KQLクエリで横断的に分析します。', answered: false },
    { word: 'Application Insights', mean: '開発者向けのアプリケーションパフォーマンス管理(APM)サービス', example: 'Application InsightsをWebアプリに組み込み、応答時間、失敗率、依存関係を監視します。', answered: false },
    { word: 'アラート ルール', mean: '監視データが特定の条件を満たしたときに、通知やアクションをトリガーするルール', example: 'VMのCPU使用率が5分間90%を超えた場合に、管理者にメールで通知するアラーとルールを設定します。', answered: false },
    { word: 'メトリック', mean: '特定の時点におけるシステムの何らかの側面を表す数値（例：CPU使用率、ネットワーク入力）', example: 'Azure Monitorでリソースのメトリックをグラフ化し、パフォーマンスの傾向を把握します。', answered: false },
    { word: 'アクティビティ ログ', mean: 'サブスクリプションレベルのイベント（リソースの作成、変更、削除など）を記録するログ', example: 'アクティビティログを調べることで、「誰が」「いつ」「何を」したかを確認できます。', answered: false },
    { word: '診断設定', mean: 'リソースから出力されるログやメトリックを、ストレージアカウントやLog Analyticsなどに転送するための設定', example: 'NSGの診断設定を有効にして、フローログをLog Analyticsワークスペースに送信し、トラフィックを分析します。', answered: false },
    { word: 'セキュリティ センター (旧称)', mean: 'Microsoft Defender for Cloudの以前の名称。セキュリティ体制管理と脅威保護機能を提供', example: '旧称はセキュリティセンターでしたが、現在はMicrosoft Defender for Cloudに統合されています。', answered: false },
    { word: 'セキュア スコア', mean: 'セキュリティに関する推奨事項に基づいて、組織のセキュリティ体制を数値化したもの', example: 'セキュアスコアを定期的に確認し、スコアを向上させるための対策を実施します。', answered: false },
    { word: '脅威インテリジェンス', mean: '既知の悪意のあるIPアドレスやドメインなどの情報源を利用して、脅威を特定する仕組み', example: 'Azure Firewallは脅威インテリジェンスフィードを利用して、悪意のあるサイトへの通信を自動的にブロックします。', answered: false },
    { word: 'サービス エンドポイント', mean: '仮想ネットワークのトラフィックを、最適化されたルートでAzureサービスに直接接続する機能', example: 'ストレージアカウントへのサービスエンドポイントを有効にすることで、VMからのトラフィックがAzureバックボーンネットワーク内にとどまります。', answered: false },
    { word: 'プライベート エンドポイント', mean: '仮想ネットワーク内に特定のAzureサービスのプライベートIPアドレスを持つNICを作成する機能', example: 'プライベートエンドポイントを作成すると、VNet内のリソースはプライベートIPを使ってPaaSサービスに接続できます。', answered: false },
    { word: 'Firewall Manager', mean: '複数のAzure Firewallのポリシーとルーティングを一元的に管理するためのサービス', example: 'Firewall Managerを使用して、組織全体のファイアウォールルールを一貫して適用します。', answered: false },
    { word: 'Azure Policy のイニシアティブ', mean: '一連のポリシー定義をグループ化し、単一のユニットとして割り当てるためのもの', example: '「HIPAAコンプライアンス」イニシアティブを作成し、関連するすべてのポリシーを一度にリソースグループに割り当てます。', answered: false },
    { word: 'コンプライアンス マネージャー', mean: '組織のコンプライアンス体制を管理し、リスク評価や改善アクションを追跡するツール', example: 'コンプライアンスマネージャーを使用して、GDPRなどの規制に対する自社の準拠状況を評価します。', answered: false },
    { word: 'データ所在地 (Data Residency)', mean: 'データが物理的に保存される地理的な場所', example: '特定の国や地域の法律により、顧客データのデータ所在地が厳しく定められている場合があります。', answered: false },
    { word: 'ISO/IEC 27001', mean: '情報セキュリティマネジメントシステム(ISMS)に関する国際規格', example: 'AzureはISO 27001認証を取得しており、高いレベルのセキュリティ管理が実施されていることを示しています。', answered: false },
    { word: 'SOC (Service Organization Controls)', mean: 'サービス組織の内部統制に関する報告書。SOC 1, 2, 3がある', example: 'SOCレポートを確認することで、Azureの運用における統制の有効性を評価できます。', answered: false },
    { word: 'GDPR (一般データ保護規則)', mean: '欧州連合(EU)におけるデータ保護とプライバシーに関する規則', example: 'EUの顧客データを扱う場合、GDPRの要件（データ主体の権利など）を遵守する必要があります。', answered: false },
    { word: 'HIPAA', mean: '米国の医療保険の相互運用性と説明責任に関する法律。医療情報の保護を規定', example: '米国の医療情報を扱うアプリケーションは、HIPAAに準拠した方法で構築・運用する必要があります。', answered: false },
    { word: 'NIST (米国国立標準技術研究所)', mean: 'サイバーセキュリティフレームワークなど、多くの標準を策定している米国の機関', example: '多くの米国政府機関は、NISTのサイバーセキュリティガイドラインに準拠することを求めています。', answered: false },
    { word: '監査ログ', mean: 'システムやアプリケーション内での操作やイベントを時系列に記録したもの', example: 'Azure ADの監査ログを確認して、ユーザーの追加や権限の変更などの操作履歴を追跡します。', answered: false },
    { word: 'アクセス レビュー', mean: 'グループのメンバーシップやリソースへのアクセス権を定期的に見直し、不要な権限を削除するプロセス', example: 'Azure ADのアクセスレビュー機能を使って、半年に一度、特権ロールの割り当てが適切かを確認します。', answered: false },
    { word: '暗号化 (転送中/保存中)', mean: 'データを転送中(in-transit)はTLS/SSLで、保存中(at-rest)はディスクレベルで暗号化し保護すること', example: 'Azureでは、データは既定で転送中も保存中も暗号化されています。', answered: false },
    { word: 'カスタマー ロックボックス', mean: 'Microsoftのエンジニアが顧客データにアクセスする必要がある場合に、顧客の明示的な承認を要求する仕組み', example: 'カスタマーロックボックスを有効にすることで、データへのアクセスを厳密に管理できます。', answered: false },
    { word: 'Advanced Threat Protection (ATP)', mean: '様々なMicrosoft製品に含まれる、高度な脅威を検出・調査するためのセキュリティソリューション群の旧ブランド名', example: '現在はMicrosoft Defenderファミリーに統合されていますが、ATPという名称が使われることもあります。', answered: false },
    { word: 'ゼロトラスト セキュリティ モデル', mean: '「決して信頼せず、常に検証する」という原則に基づき、すべてのアクセス要求を厳格に検証するアプローチ', example: 'ゼロトラストモデルでは、社内ネットワークからのアクセスであっても、信頼せず多要素認証などを要求します。', answered: false },
    { word: 'Azure SQL Managed Instance', mean: 'オンプレミスのSQL Serverとの高い互換性を持つ、フルマネージドなPaaSデータベースサービス', example: '既存のSQL Serverアプリケーションを、ほぼコード変更なしでSQL Managed Instanceに移行しました。', answered: false },
    { word: 'Azure Database for MariaDB', mean: 'オープンソースのMariaDBをベースにした、フルマネージドなリレーショナルデータベースサービス', example: 'オンプレミスのMariaDBを、運用負荷の低いAzure Database for MariaDBにリフト＆シフトします。', answered: false },
    { word: 'SQL Server on Azure VMs', mean: 'Azureの仮想マシン上にSQL Serverをインストールして利用するIaaSモデル', example: 'OSレベルでの完全な制御が必要な場合や、特定のバージョンが必要な場合にSQL Server on Azure VMsを選択します。', answered: false },
    { word: 'エラスティック プール', mean: '複数のAzure SQL Databaseでリソース（DTU/vCore）を共有し、コストを最適化する仕組み', example: '利用量に波がある複数のデータベースをエラスティックプールにまとめることで、個別にプロビジョニングするよりコストを抑えられます。', answered: false },
    { word: 'データ ウェアハウス (DWH)', mean: '分析や意思決定のために、様々なソースからデータを集約・格納する大規模なリポジトリ', example: 'Azure Synapse Analyticsは、最新のクラウドデータウェアハウスソリューションです。', answered: false },
    { word: 'Azure Data Lake Storage', mean: 'ビッグデータ分析のために、あらゆるサイズ・形式のデータを格納できる、スケーラブルなストレージ', example: '大量の生ログデータを、加工せずにそのままData Lake Storageに投入し、後から分析に利用します。', answered: false },
    { word: 'Azure Data Factory', mean: 'データの移動と変換をオーケストレーションする、クラウドベースのETL/ELTサービス', example: 'Data Factoryのパイプラインを作成し、オンプレミスのDBからAzure Synapseへ定期的にデータをロードします。', answered: false },
    { word: 'Azure HDInsight', mean: 'Apache Hadoop, Spark, KafkaなどのオープンソースフレームワークをAzure上で利用できるマネージドサービス', example: 'HDInsightを使用して、大規模なデータセットに対して分散処理を行うSparkジョブを実行します。', answered: false },
    { word: 'Azure Stream Analytics', mean: 'リアルタイムのデータストリームを処理・分析するためのイベント処理エンジン', example: 'IoTデバイスから送られてくるセンサーデータを、Stream Analyticsでリアルタイムに分析し、異常を検知します。', answered: false },
    { word: 'Power BI', mean: '様々なデータソースに接続し、インタラクティブなレポートやダッシュボードを作成できるビジネス分析ツール', example: 'Azure SQL DatabaseのデータをPower BIで可視化し、売上の傾向を分析します。', answered: false },
    { word: 'Azure Analysis Services', mean: 'Power BIやExcelでの高速な分析を可能にする、エンタープライズグレードのBIセマンティックモデルを提供するPaaS', example: '大規模なデータセットからセマンティックモデルを構築し、ユーザーが自由にデータを探索できるようにします。', answered: false },
    { word: 'Azure Cognitive Search', mean: 'AIを活用した検索機能をアプリケーションに組み込むためのPaaS。旧称Azure Search', example: 'Cognitive Searchを使い、ドキュメント内のテキストだけでなく、画像内の文字も検索対象に含めます。', answered: false },
    { word: 'NoSQL', mean: 'リレーショナルデータベース以外のデータベースの総称。柔軟なスキーマや水平スケーラビリティが特徴', example: 'Cosmos DBは、ドキュメント、キーバリュー、グラフなど複数のモデルをサポートするNoSQLデータベースです。', answered: false },
    { word: 'リレーショナル データベース (RDB)', mean: '行と列からなるテーブル形式でデータを格納し、SQLで操作する伝統的なデータベース', example: 'Azure SQL Databaseは、代表的なクラウドベースのリレーショナルデータベースです。', answered: false },
    { word: 'グローバル分散', mean: '世界中の複数のAzureリージョンにデータを分散配置し、ユーザーに近い場所から高速なアクセスを提供する機能', example: 'Cosmos DBのグローバル分散機能を使えば、ボタンクリック一つでデータを世界中にレプリケートできます。', answered: false },
    { word: 'Azure Bot Service', mean: 'インテリジェントなボットを構築、テスト、デプロイ、管理するための統合開発環境', example: 'Bot ServiceとQnA Makerを組み合わせて、よくある質問に自動で回答するFAQボットを作成します。', answered: false },
    { word: 'Computer Vision API', mean: '画像から情報を抽出する（物体の検出、顔認識、OCRなど）ためのAIサービス', example: 'Computer Vision APIを使って、写真に写っているランドマークの名前を特定するアプリを開発します。', answered: false },
    { word: 'Face API', mean: '画像から人間の顔を検出、認識、分析するためのAIサービス', example: 'Face APIを利用して、写真に写っている人物の年齢や感情を推定します。', answered: false },
    { word: 'Language Understanding (LUIS)', mean: '自然言語のテキストからユーザーの意図（Intent）や情報（Entity）を抽出するAIサービス', example: 'LUISを使って、「明日の東京の天気を教えて」という発話から、「天気予報」という意図と「明日」「東京」というエンティティを抽出します。', answered: false },
    { word: 'QnA Maker', mean: '既存のFAQドキュメントなどから、簡単に対話型のQ&Aボットを作成できるAIサービス', example: '社内のITサポートに関するFAQページをQnA Makerに取り込み、問い合わせ対応ボットを数分で作成しました。', answered: false },
    { word: 'Speech Services', mean: '音声認識（Speech-to-Text）と音声合成（Text-to-Speech）の機能を提供するAIサービス', example: 'Speech Servicesを使って、会議の音声をリアルタイムでテキスト化し、議事録を自動作成します。', answered: false },
    { word: 'Text Analytics API', mean: 'テキストから感情分析、キーフレーズ抽出、言語検出などを行うAIサービス', example: '製品レビューのテキストをText Analytics APIで分析し、顧客の感情（ポジティブ/ネガティブ）を把握します。', answered: false },
    { word: 'Translator', mean: 'テキストやドキュメントをリアルタイムで多言語に翻訳するAIサービス', example: 'Translator APIをWebサイトに組み込み、コンテンツを世界中のユーザーの言語に自動翻訳します。', answered: false },
    { word: 'パーソナライザー', mean: 'ユーザーの行動から学習し、各ユーザーに最適なコンテンツや体験を提供するAIサービス', example: 'ニュースサイトでパーソナライザーを使い、各ユーザーの興味に合わせた記事をおすすめ表示します。', answered: false },
    { word: '自動機械学習 (Automated ML)', mean: 'データに最適な機械学習モデルとハイパーパラメータを自動的に選択・構築する機能', example: 'プログラミングの知識がなくても、Automated MLを使って高精度な需要予測モデルを作成できました。', answered: false },
    { word: 'Azure IoT Central', mean: 'IoTソリューションの構築を簡素化する、フルマネージドなSaaS型IoTアプリケーションプラットフォーム', example: 'IoT Centralのテンプレートを使い、コーディングなしで遠隔地のデバイスを監視するアプリケーションを構築します。', answered: false },
    { word: 'Azure IoT Edge', mean: 'クラウドの分析やビジネスロジックを、コンテナ化してIoTデバイス上で直接実行するサービス', example: 'IoT Edgeを使い、カメラ映像をクラウドに送る前にデバイス上で異常検知処理を行い、通信量を削減します。', answered: false },
    { word: 'Azure Sphere', mean: 'セキュアなMCU、OS、クラウドサービスを統合し、コネクテッドデバイスのセキュリティを確保するソリューション', example: 'Azure Sphereを搭載した家電製品は、OSの更新や脅威検出がクラウドから行われ、安全性が高く保たれます。', answered: false },
    { word: 'Azure Time Series Insights', mean: 'IoTデバイスなどから生成される大量の時系列データを格納、可視化、分析するためのサービス', example: 'Time Series Insightsを使い、工場全体のセンサーデータから生産効率のボトルネックを特定します。', answered: false },
    { word: 'Azure Repos', mean: 'プライベートなGitリポジトリを提供する、Azure DevOpsのコンポーネント', example: 'プロジェクトのソースコードをAzure Reposで管理し、チームで共同開発を進めています。', answered: false },
    { word: 'Azure Pipelines', mean: 'あらゆる言語、プラットフォーム、クラウドに対応したCI/CD（継続的インテグレーション/デプロイ）サービス', example: 'Azure Pipelinesで、コードのプッシュをトリガーに自動でビルド、テスト、Azureへのデプロイを実行します。', answered: false },
    { word: 'Azure Boards', mean: 'アジャイル開発（かんばんボード、バックログ、ダッシュボード）を支援する作業追跡ツール', example: 'Azure Boardsを使って、スプリント計画を立て、ユーザーストーリーやタスクの進捗を管理します。', answered: false },
    { word: 'Azure Test Plans', mean: '手動テストおよび探索的テストの計画、実行、追跡を支援するツール', example: 'Azure Test Plansでテストケースを管理し、リリース前の品質を確保します。', answered: false },
    { word: 'Azure Artifacts', mean: 'Maven, npm, NuGetなどのパッケージフィードを作成・共有し、パッケージ管理を一元化するサービス', example: '社内共通のライブラリをAzure Artifactsで管理し、複数のプロジェクトから参照できるようにします。', answered: false },
    { word: 'GitHub', mean: '世界最大級のソフトウェア開発プラットフォーム。Microsoftに買収され、Azureとの連携が強化されている', example: '多くのオープンソースプロジェクトがGitHub上で開発されており、Azure DevOpsとの連携も可能です。', answered: false },
    { word: 'GitHub Actions for Azure', mean: 'GitHubリポジトリから直接、AzureへのCI/CDワークフローを構築・実行できる機能', example: 'GitHub Actionsを使い、リポジトリへのコミットをトリガーにAzure App Serviceへ自動でデプロイします。', answered: false },
    { word: 'Infrastructure as Code (IaC)', mean: 'インフラ（ネットワーク、VM、DBなど）を、コード（ARMテンプレート、Terraformなど）で定義・管理する手法', example: 'IaCを実践することで、インフラ構成の再現性を高め、手動での設定ミスを防ぎます。', answered: false },
    { word: '継続的インテグレーション (CI)', mean: '開発者がコード変更を頻繁に中央リポジトリにマージし、そのたびに自動でビルドとテストを実行するプラクティス', example: 'CIを導入することで、統合時の問題を早期に発見し、開発サイクルを高速化します。', answered: false },
    { word: '継続的デリバリー/デプロイメント (CD)', mean: 'CIのプロセスを経て、変更を自動的にテスト環境や本番環境にリリースするプラクティス', example: '継続的デプロイメントを実現すると、変更がリポジトリにマージされた後、人手を介さずに本番環境まで反映されます。', answered: false },
    { word: 'ARM テンプレート スペック', mean: 'ARMテンプレートを組織内で再利用可能なリソースとして保存・共有するための機能', example: '標準的なVM構成をテンプレートスペックとして登録し、誰でも簡単に同じ構成のVMをデプロイできるようにします。', answered: false },
    { word: 'App Service プラン', mean: 'App Serviceで実行されるWebアプリのコンピューティングリソース（リージョン、VMサイズ、スケール数）を定義するもの', example: '同じApp Serviceプラン内の複数のアプリは、同じコンピューティングリソースを共有します。', answered: false },
    { word: 'デプロイ スロット', mean: '本番環境とは別のステージング環境にアプリをデプロイし、テスト後にトラフィックをスワップできる機能', example: 'デプロイスロットを使うことで、ダウンタイムなしでアプリケーションの新しいバージョンをリリースできます。', answered: false },
    { word: 'カスタム ドメイン', mean: 'Azure App Serviceで作成したWebアプリに、デフォルトのURLの代わりに独自のドメイン名を設定する機能', example: '「www.contoso.com」のようなカスタムドメインをWebアプリにマッピングします。', answered: false },
    { word: 'SSL/TLS 証明書', mean: 'Webサイトとユーザー間の通信を暗号化し、サイトの信頼性を保証するための電子証明書', example: 'App ServiceにSSL証明書をバインドし、HTTPS通信を有効にします。', answered: false },
    { word: 'API Management', mean: '既存のバックエンドサービスに対するAPIゲートウェイを作成し、公開、保護、分析を行うためのサービス', example: 'API Managementを使い、APIの利用状況を監視したり、アクセスキーで利用者を制限したりします。', answered: false },
    { word: 'Azure SignalR Service', mean: 'リアルタイムのWeb機能をアプリケーションに簡単に追加できるフルマネージドサービス', example: 'SignalR Serviceを使って、サーバーから複数のクライアントにリアルタイムでデータをプッシュするチャットアプリを構築します。', answered: false },
    { word: 'Azure Notification Hubs', mean: 'iOS, Android, Windowsなど、あらゆるプラットフォームのモバイルデバイスにプッシュ通知を送信するエンジン', example: 'Notification Hubsを使い、セール情報を数百万人のユーザーのスマートフォンに一斉に通知します。', answered: false },
    { word: 'WebJobs', mean: 'App Serviceのコンテキストで、バックグラウンドで実行されるプログラム（スクリプトや実行可能ファイル）', example: '定期的なデータクリーンアップ処理を、スケジュールされたWebJobとして実行します。', answered: false },
    { word: '静的 Web アプリ (Static Web Apps)', mean: '静的なHTML/CSS/JSファイルとサーバーレスAPIからなる最新のWebアプリをホスト・ビルド・デプロイするサービス', example: 'GitHubリポジトリと連携し、Reactアプリをビルドしてグローバルに配信するプロセスを自動化します。', answered: false },
    { word: 'イベント駆動型アーキテクチャ', mean: 'イベント（状態の変化）の発生、検出、消費を中心として設計されたソフトウェアアーキテクチャ', example: 'Azure FunctionsやEvent Gridは、イベント駆動型アーキテクチャを構築するための中心的なサービスです。', answered: false },
    { word: '予算 (Budgets)', mean: 'Azureのコストを管理するために、特定のスコープ（サブスクリプションなど）に対して設定する金額のしきい値', example: 'サブスクリプションに予算を設定し、コストが予算の80%に達したらアラートを受け取るようにします。', answered: false },
    { word: 'コスト アラート', mean: 'Azureのコストが設定したしきい値を超えたときに通知を送信する機能', example: '予期せぬコストの増加を早期に検知するために、コストアラートは必須の設定です。', answered: false },
    { word: 'コスト分析', mean: 'Azure Cost Management内のツールで、組織のコストを詳細に分析・可視化する機能', example: 'コスト分析を使い、どのサービスやリソースグループがコストの大部分を占めているかを特定します。', answered: false },
    { word: '予約 (Reservations)', mean: '特定のサービス（VM、ストレージなど）を1年または3年の期間で事前購入し、従量課金制に比べて大幅な割引を受ける仕組み', example: '常に稼働している本番環境のVMに対して予約を購入し、コストを最適化します。', answered: false },
    { word: 'Azure Advisor のコスト推奨事項', mean: 'アイドル状態のリソースや、サイズが過大なVMなど、コスト削減の機会を自動的に提示する機能', example: 'Advisorの推奨に従って、使用されていないパブリックIPアドレスを削除し、コストを削減しました。', answered: false },
    { word: 'Basic サポートプラン', mean: 'すべてのAzure顧客に無料で含まれる、課金とサブスクリプション管理のサポートのみを提供するプラン', example: 'Basicプランでは、技術的な問題に関するサポートは受けられません。', answered: false },
    { word: 'Developer サポートプラン', mean: '非本番環境での試用や開発者向けの、営業時間内のみの技術サポートを提供する低コストのプラン', example: '開発中のプロジェクトで技術的な質問があるため、Developerサポートプランに加入しました。', answered: false },
    { word: 'Standard サポートプラン', mean: '本番環境のワークロード向けのプランで、24時間365日の技術サポートを提供する', example: '企業の基幹システムをAzureで運用する場合、Standard以上のサポートプランが推奨されます。', answered: false },
    { word: 'Professional Direct サポートプラン', mean: 'ビジネスクリティカルなワークロード向けに、より迅速な応答時間とプロアクティブなサポートを提供するプラン', example: 'ProDirectプランでは、専任のサポートエンジニアによるアドバイスも受けられます。', answered: false },
    { word: 'Premier/Unified サポートプラン', mean: '大規模な組織向けに、包括的なサポートとコンサルティングを提供する最上位のプラン', example: 'Unifiedサポートは、Azureだけでなく、Microsoft製品全体をカバーするサポート契約です。', answered: false },
    { word: 'サービス クレジット', mean: 'SLAで定められた稼働率を下回った場合に、影響を受けた顧客に対して提供される料金の割引', example: '先月のサービス障害によりSLAが未達だったため、今月の請求でサービスクレジットが適用されました。', answered: false },
    { word: '複合 SLA', mean: '複数のサービスを組み合わせてアプリケーションを構築した場合の、全体のSLA', example: '複合SLAは、各サービスのSLAを掛け合わせることで計算され、個々のSLAよりも低くなります（例: 99.95% * 99.99%）。', answered: false },
    { word: 'プレビュー機能', mean: '一般提供（GA）の前に、評価目的で公開される新機能。SLAは適用されないことが多い', example: 'プレビュー機能は本番環境での利用は推奨されませんが、新技術をいち早く試すことができます。', answered: false },
    { word: '一般提供 (GA)', mean: '機能やサービスが正式にリリースされ、すべての顧客が利用可能で、SLAが適用される状態', example: '長らくプレビューだった新機能が、ついにGA（General Availability）になりました。', answered: false },
    { word: 'Azure の更新情報 (Azure Updates)', mean: 'Azureの製品やサービスの重要な更新（新機能、廃止予定など）が公開される公式チャネル', example: '定期的にAzure Updatesをチェックして、利用中のサービスへの影響を確認することが重要です。', answered: false },
    { word: 'UDR (ユーザー定義ルート)', mean: 'Azureのデフォルトのルーティングを上書きし、トラフィックのネクストホップを制御するためのルート', example: 'UDRを設定して、サブネットからのすべてのインターネット向けトラフィックをファイアウォールアプライアンスに強制します。', answered: false },
    { word: 'BGP (Border Gateway Protocol)', mean: 'ExpressRouteやVPN Gatewayで、オンプレミスとAzureのネットワーク間で動的にルート情報を交換するためのプロトコル', example: 'BGPを使用すると、オンプレミス側でネットワーク変更があった場合も、Azure側で手動でルートを更新する必要がありません。', answered: false },
    { word: '仮想 WAN (Virtual WAN)', mean: 'ブランチオフィス、データセンター、VNetなどを接続するための、大規模なネットワークハブをAzureで構築するサービス', example: 'Virtual WANを使い、グローバルに展開する拠点のネットワーク接続を簡素化し、一元管理します。', answered: false },
    { word: 'Azure Front Door', mean: 'Webアプリケーションのグローバルなルーティングと高速化、セキュリティを提供する最新のCDNサービス', example: 'Front Doorを使用して、ユーザーを最も低遅延のバックエンドにルーティングし、DDoS攻撃から保護します。', answered: false },
    { word: 'ネットワークウォッチャー', mean: 'Azureのネットワークの監視、診断、ログ収集を行うためのツール群', example: 'ネットワークウォッチャーのIPフロー確認機能を使って、NSGルールによって通信がブロックされている原因を特定します。', answered: false },
    { word: 'IP フローの確認', mean: '特定のVMとの間で、指定したIPアドレス・ポート間の通信が許可されているか拒否されているかを確認する機能', example: 'VM間の通信ができない場合、まずIPフローの確認ツールでNSGの設定をチェックします。', answered: false },
    { word: '接続のトラブルシューティング', mean: '2つのエンドポイント間の接続性をテストし、問題を診断するためのツール', example: 'VMから特定のURLへの接続に問題がある場合、接続のトラブルシューティングで原因を切り分けます。', answered: false },
    { word: 'NSG フロー ログ', mean: 'NSGを通過するIPトラフィックに関する情報を記録する機能', example: 'NSGフローログを有効にし、Log Analyticsで分析することで、不審なトラフィックパターンを検出します。', answered: false },
    { word: '強制トンネリング', mean: 'サブネットからのすべてのインターネット向けトラフィックを、オンプレミス経由でルーティングするように強制する構成', example: 'セキュリティポリシー上、すべてのトラフィックをオンプレミスのプロキシで検査する必要がある場合に強制トンネリングを使用します。', answered: false },
    { word: 'サービス タグ', mean: '特定のAzureサービスに対応するIPアドレスプレフィックスのグループを表すラベル（例: Storage.EastUS）', example: 'NSGのルールで、宛先にサービスタグを指定することで、IPアドレスの変更に自動で追従できます。', answered: false },
    { word: 'アクセス層 (ホット/クール/アーカイブ)', mean: 'BLOBストレージのコストと可用性を最適化するための3つの層。ストレージ層とも呼ばれる', example: 'アクセス層を適切に使い分けることで、ストレージコストを大幅に削減できます。', answered: false },
    { word: 'ライフサイクル管理ポリシー', mean: 'BLOBデータが特定の条件を満たした場合に、自動的にアクセス層を移動させたり削除したりするルール', example: '「作成から30日経過したデータをクール層に移動し、180日経過したらアーカイブ層に移動する」というポリシーを設定します。', answered: false },
    { word: '静的 Web サイト ホスティング (ストレージ)', mean: 'Azure Storageアカウントから直接、HTML/CSS/JSなどの静的コンテンツを配信する機能', example: '簡単なWebサイトを、サーバーを立てずにストレージアカウントの静的Webサイト機能で公開しました。', answered: false },
    { word: 'Shared Access Signature (SAS)', mean: 'ストレージリソースへの委任されたアクセスを提供する、期間限定のセキュアなURI', example: 'ユーザーにSASトークンを発行し、特定のBLOBコンテナに1時間だけアップロードする権限を与えます。', answered: false },
    { word: '保存時の暗号化 (SSE)', mean: 'データがAzure Storageに書き込まれる際に自動的に暗号化される機能', example: 'Azure Storageでは、SSEがデフォルトで有効になっており、ユーザーが意識しなくてもデータは保護されます。', answered: false },
    { word: 'Azure NetApp Files', mean: 'エンタープライズグレードの高性能なファイルストレージを必要とするワークロード向けのPaaSサービス', example: '高いIOPSが求められるSAP HANAなどのアプリケーションの共有ストレージとして、Azure NetApp Filesを利用します。', answered: false },
    { word: 'Avere vFXT for Azure', mean: 'ハイパフォーマンスコンピューティング(HPC)向けに、ストレージの読み取りパフォーマンスを高速化するキャッシングソリューション', example: '大規模なレンダリングファームで、Avere vFXTを使ってデータへのアクセスを高速化します。', answered: false },
    { word: 'StorSimple', mean: 'オンプレミスのストレージとAzure Storageを統合するハイブリッドクラウドストレージソリューション（旧製品）', example: 'StorSimpleは、アクセス頻度の低いデータを自動的にクラウドに階層化します。', answered: false },
    { word: 'Premium Storage', mean: 'SSDベースの高性能なディスクストレージで、高いIOPSと低遅延を必要とするVMワークロード向け', example: '本番環境のSQL Serverのデータベースファイルは、Premium Storage上に配置します。', answered: false },
    { word: 'Standard SSD/HDD', mean: '開発/テスト環境や、パフォーマンス要件がそれほど高くないワークロード向けの、コスト効率の良いディスクストレージ', example: 'Standard SSDは、低IOPSのWebサーバーなどに適しています。Standard HDDはバックアップ用途などに使われます。', answered: false },
    { word: '近接配置グループ', mean: 'Azure VMを物理的に互いに近くに配置し、VM間のネットワーク遅延を最小化するための論理的なグループ', example: '多層アプリケーションのVMを同じ近接配置グループにデプロイして、層間の通信を高速化します。', answered: false },
    { word: 'VM の世代 (Gen1/Gen2)', mean: '仮想マシンのアーキテクチャ。Gen2はUEFIベースの新しい形式で、大容量ディスクなどの利点がある', example: '新しいVMを作成する際は、特別な理由がなければGen2を選択することが推奨されます。', answered: false },
    { word: 'エフェメラル OS ディスク', mean: 'VMのホストマシンのローカルストレージ（キャッシュなど）に作成される、永続性のないOSディスク', example: 'エフェメラルOSディスクは高速ですが、VMの再割り当てなどでデータが失われるため、ステートレスなアプリに適しています。', answered: false },
    { word: 'ブート診断', mean: 'VMの起動に関する問題のトラブルシューティングに役立つ、コンソールのスクリーンショットとログを収集する機能', example: 'VMが起動しない場合、まずブート診断のスクリーンショットを確認してエラーメッセージを調べます。', answered: false },
    { word: 'シリアル コンソール', mean: 'VMのシリアルポートへのテキストベースのコンソールアクセスを提供する機能', example: 'ネットワーク接続が失われたVMでも、シリアルコンソールを使ってログインし、トラブルシューティングを行うことができます。', answered: false },
    { word: 'カスタム スクリプト拡張機能', mean: 'VMの初回起動時やプロビジョニング後に、スクリプト（PowerShell, Bashなど）をダウンロードして実行する機能', example: 'カスタムスクリプト拡張機能を使って、VM作成時に必要なソフトウェアを自動でインストールします。', answered: false },
    { word: 'Azure Batch', mean: '大規模な並列コンピューティングやハイパフォーマンスコンピューティング(HPC)のジョブをクラウドで実行するサービス', example: 'Azure Batchを使って、数千コアのVMプールで財務リスクモデリングの計算を実行します。', answered: false },
    { word: 'CycleCloud', mean: 'エンタープライズ環境でHPCクラスターの作成、管理、最適化を簡素化するツール', example: 'CycleCloudを使い、特定のジョブスケジューラ（Slurmなど）を持つHPC環境をAzure上に簡単に構築します。', answered: false },
    { word: 'HPC (ハイパフォーマンス コンピューティング)', mean: '非常に高い計算能力を必要とする、科学技術計算やシミュレーションなどの分野', example: 'Azureは、InfiniBandを搭載したHPC向けのVMインスタンスを提供しています。', answered: false },
    { word: 'SAP on Azure', mean: 'ミッションクリティカルなSAPワークロードをAzure上で実行するための、認定されたインフラとサービス', example: '多くの企業が、自社のSAPシステムをオンプレミスからSAP on Azureに移行しています。', answered: false },
    { word: 'Azure Resource Graph', mean: 'Kustoクエリ言語を使って、複数のサブスクリプションにまたがるAzureリソースを高速に探索・照会するサービス', example: 'Resource Graphを使い、「特定のタグが付いたすべてのVM」を数秒で一覧表示します。', answered: false },
    { word: 'Azure Lighthouse', mean: 'サービスプロバイダーが、複数の顧客のAzure環境を単一のコントロールプレーンから管理できるようにするサービス', example: 'マネージドサービスプロバイダー(MSP)は、Lighthouseを使って顧客のテナントを安全かつ効率的に管理します。', answered: false },
    { word: 'Azure Resource Mover', mean: 'Azureリソースをリージョン間で移動させるための支援ツール', example: 'Resource Moverを使って、関連するリソースの依存関係を分析し、安全に別のリージョンに移動させます。', answered: false },
    { word: 'Azure Chaos Studio', mean: 'アプリケーションの回復性を向上させるために、意図的に障害を発生させてテストする（カオスエンジニアリング）ためのPaaS', example: 'Chaos Studioを使って、VMの突然のシャットダウンをシミュレートし、アプリケーションが正しくフェールオーバーするかをテストします。', answered: false },
    { word: 'Azure Automanage', mean: '仮想マシンのライフサイクル全体にわたって、構成や管理のベストプラクティスを自動的に適用するサービス', example: 'Automanageを有効にするだけで、バックアップ、監視、セキュリティ設定などが自動的に構成されます。', answered: false },
    { word: 'Azure Well-Architected Framework', mean: '高品質なクラウドソリューションを設計するための、5つの柱（コスト、運用、性能、信頼性、セキュリティ）からなる指針', example: 'システム設計時には、常にWell-Architected Frameworkの原則を意識することが重要です。', answered: false },
    { word: 'コストの最適化 (Pillar)', mean: 'Well-Architected Frameworkの柱の一つ。不要な費用をなくし、ビジネス価値を最大化することに焦点を当てる', example: 'リソースの適切なサイジングや予約の活用は、コストの最適化の重要な要素です。', answered: false },
    { word: 'オペレーショナル エクセレンス (Pillar)', mean: 'Well-Architected Frameworkの柱の一つ。アプリケーションを本番環境で運用するためのプロセスと手順に関するもの', example: 'IaCや監視、自動化を導入することで、オペレーショナルエクセレンスを実現します。', answered: false },
    { word: 'パフォーマンス効率 (Pillar)', mean: 'Well-Architected Frameworkの柱の一つ。需要の変化に対応して、効率的にスケールできるシステムの能力', example: '適切なスケーリング戦略を選択し、負荷テストを行うことがパフォーマンス効率の鍵です。', answered: false },
    { word: '信頼性 (Pillar)', mean: 'Well-Architected Frameworkの柱の一つ。障害から回復し、処理を継続できるシステムの能力', example: '冗長性の確保、障害のテスト、自己修復機能の実装などが信頼性を高めます。', answered: false },
    { word: 'セキュリティ (Pillar)', mean: 'Well-Architected Frameworkの柱の一つ。脅威からシステムとデータを保護すること', example: 'ID管理、インフラ保護、暗号化など、多層防御のアプローチでセキュリティを確保します。', answered: false },
    { word: 'Microsoft Cloud Adoption Framework for Azure', mean: '組織がクラウド導入を成功させるための、実証済みのガイダンス、ドキュメント、ツール群', example: 'Cloud Adoption Frameworkは、戦略、計画、準備、導入、統制、管理の各フェーズで構成されています。', answered: false },
    { word: 'ランディング ゾーン', mean: '新しいアプリケーションをデプロイするための、事前にプロビジョニングされたAzure環境。ネットワーク、ID、ガバナンスなどが設定済み', example: 'ランディングゾーンを用意することで、開発チームはインフラの準備を待たずに、迅速に開発を開始できます。', answered: false },
    { word: 'デプロイ スタンプ パターン', mean: 'アプリケーションのコンポーネント群を、単一のユニット（スタンプ）として繰り返しデプロイするアーキテクチャパターン', example: 'このパターンは、マルチテナントSaaSアプリケーションや、地理的に分散したデプロイに適しています。', answered: false },
    { word: 'テナント', mean: 'Azure ADにおいて、組織を表す専用のインスタンス。ディレクトリとも呼ばれる', example: '新しい会社は、まずAzure ADで自社のテナントを作成します。', answered: false },
    { word: 'ディレクトリ', mean: 'Azure ADのインスタンスのことで、ユーザー、グループ、アプリケーションなどのオブジェクトを格納する', example: 'テナントは、単一のディレクトリを持ちます。', answered: false },
    { word: 'フェデレーション', mean: '異なるID管理システム間で信頼関係を構築し、ユーザーが一方のシステムでの認証情報を使って他方のシステムにアクセスできるようにすること', example: 'オンプレミスのAD FSとAzure ADをフェデレーション構成にすることで、シームレスなSSOを実現します。', answered: false },
    { word: 'クレーム', mean: 'ユーザーに関する情報（名前、メールアドレス、役割など）を含む、IDプロバイダーが発行するキーと値のペア', example: '認証が成功すると、Azure ADはユーザーのクレームを含むIDトークンを発行します。', answered: false },
    { word: 'OAuth 2.0', mean: 'Webサイトやアプリケーションが、ユーザーの代わりにリソースへのアクセス許可を得るための認可フレームワーク', example: '多くのAPIは、OAuth 2.0を使用してアクセスを保護しています。', answered: false },
    { word: 'OpenID Connect', mean: 'OAuth 2.0をベースにした、シンプルなIDレイヤー。認証を行い、ユーザーに関する基本プロファイル情報を取得できる', example: 'OpenID Connectは、今日のWebサイトやモバイルアプリで広く使われている認証プロトコルです。', answered: false },
    { word: 'SAML (Security Assertion Markup Language)', mean: 'IDプロバイダーとサービスプロバイダー間で認証・認可データを交換するためのXMLベースの標準', example: 'SAMLは、特にエンタープライズ向けのSSOでよく利用されます。', answered: false },
    { word: 'サービス正常性アラート', mean: 'Azure Service Healthで、利用中のサービスに影響する問題が発生した場合に通知を受け取るためのアラート', example: '重要なサービスについては、サービス正常性アラートを構成しておくことが強く推奨されます。', answered: false },
    { word: 'リソース正常性', mean: '個々のリソース（VMなど）の正常性状態に関する情報を提供するAzure Monitorの機能', example: 'リソース正常性ログを確認することで、プラットフォーム側の問題でVMが再起動されたかどうかなどを把握できます。', answered: false },
    { word: 'Azure China 21Vianet', mean: '中国国内で、21Vianet社によって独立して運営されているAzureサービス', example: '中国の法律と規制に準拠するため、中国国内の顧客向けサービスはAzure China 21Vianet上で展開します。', answered: false },
    { word: 'Azure Germany', mean: 'ドイツのデータ主権要件を満たすために提供されていた特別なAzureリージョン。現在は新規受付を終了', example: 'Azure Germanyは、ドイツのデータトラスティが管理する閉じた環境でした。', answered:false },
    { word: '国/リージョン別の利用可能性', mean: 'Azureの各サービスが、どのリージョンで利用可能かを示す情報', example: '新しいサービスを検討する際は、まず利用したいリージョンでの利用可能性を確認する必要があります。', answered: false },
    { word: 'オンライン サービス条件 (OST)', mean: 'Microsoftの商用オンラインサービス（Azure, M365など）に適用される、法的な契約条件', example: 'OSTには、データ処理やセキュリティに関するMicrosoftのコミットメントが記載されています。', answered: false },
    { word: 'データ保護補遺 (DPA)', mean: 'オンラインサービス条件を補足し、データプライバシーとセキュリティに関する詳細な条件を定めた文書', example: 'DPAには、GDPRなどの規制に対応するための条項が含まれています。', answered: false },
    { word: 'Microsoft プライバシー ステートメント', mean: 'Microsoftがどのような個人データを収集し、どのように利用するかを説明する文書', example: 'プライバシーステートメントを読むことで、Microsoftのデータ取り扱い方針を理解できます。', answered: false },
    { word: 'Azure Monitor for VMs', mean: '仮想マシンのパフォーマンスと正常性を大規模に監視するためのソリューション', example: 'Azure Monitor for VMsを有効にすると、VMのパフォーマンスチャートや依存関係マップを簡単に表示できます。', answered: false },
    { word: 'Azure Monitor for Containers', mean: 'AKSなどのコンテナ化されたワークロードのパフォーマンスを監視するためのソリューション', example: 'Azure Monitor for Containersで、クラスター、ノード、ポッド、コンテナのパフォーマンスを詳細に分析します。', answered: false },
    { word: 'Kusto クエリ言語 (KQL)', mean: 'Azure MonitorのログデータやAzure Resource Graphを照会するために使用される、読み取り専用の強力なクエリ言語', example: 'KQLを習得することで、ログから必要な情報を効率的に抽出できます。', answered: false },
    { word: 'ワークブック (Azure Monitor)', mean: 'テキスト、クエリ、メトリック、パラメータを組み合わせて、インタラクティブな視覚レポートを作成する機能', example: 'ワークブックを使い、特定のアプリケーションの正常性を一覧できるカスタムダッシュボードを作成します。', answered: false },
    { word: '変更の追跡とインベントリ', mean: 'Azure Automationの機能で、VMのソフトウェア、ファイル、レジストリなどの変更を追跡し、インベントリを収集する', example: 'この機能を使うことで、意図しない構成変更が加えられた場合にそれを検知できます。', answered: false },
    { word: '状態の構成 (Azure Automation State Configuration)', mean: 'PowerShell Desired State Configuration (DSC) を利用して、VMの構成を一貫して管理・監視するサービス', example: 'State Configurationを使い、すべてのWebサーバーにIISがインストールされ、特定の構成が適用されている状態を維持します。', answered: false },
];
